### ISSUE TITLE
paper with list of materials databases

### ISSUE THREAD

**Issue by ltalirz** [tilde-lab/awesome-materials-informatics#13]
very interesting reference from 2010 with an overview of existing materials databases
http://iopscience.iop.org/article/10.1070/RC2010v079n02ABEH004104/meta

we should check whether we are missing any

**Comment by blokhin** [comment]
Wow! Posting the listing here... probably should delete in a while, to avoid copyright violation issues.

![2019-01-21_13-14-16](https://user-images.githubusercontent.com/177388/51474248-f4b38000-1d7e-11e9-97ae-1110bd8fac3a.png)
![2019-01-21_13-14-38](https://user-images.githubusercontent.com/177388/51474244-f4b38000-1d7e-11e9-895d-f788c34fd1bc.png)
![2019-01-21_13-14-53](https://user-images.githubusercontent.com/177388/51474241-f41ae980-1d7e-11e9-9709-39fa90b0f9cd.png)
![2019-01-21_13-15-10](https://user-images.githubusercontent.com/177388/51474240-f41ae980-1d7e-11e9-8e60-c3b7758fc9a0.png)
![2019-01-21_13-15-28](https://user-images.githubusercontent.com/177388/51474239-f3825300-1d7e-11e9-9399-fa0365127237.png)
![2019-01-21_13-15-45](https://user-images.githubusercontent.com/177388/51474238-f3825300-1d7e-11e9-8235-37d2c7267eaf.png)
![2019-01-21_13-16-05](https://user-images.githubusercontent.com/177388/51474237-f3825300-1d7e-11e9-95af-b525b87f27d9.png)
![2019-01-21_13-16-24](https://user-images.githubusercontent.com/177388/51474235-f2e9bc80-1d7e-11e9-8940-a58cb821ce05.png)

**Comment by ltalirz** [comment]
There's now also an online version on http://en.iric.imet-db.ru

**Comment by blokhin** [comment]
Now added here: https://github.com/tilde-lab/awesome-materials-informatics#similar-compilations
thanks for pointing this out, @ltalirz
