### ISSUE TITLE
Dataset for Common Monomer Repeating Units for polymers and common groups for clay from IUPAC to SMILES/SMARTS

### ISSUE THREAD

**Issue by Sulstice** [tilde-lab/awesome-materials-informatics#50]
Hello, 

I have been maintaining lists of common functional groups for different diverse communities. For materials the lists I have are:

Common Functional groups for Clay Adsorption: https://github.com/Sulstice/global-chem/blob/master/global_chem/global_chem/materials/clay/montmorillonite_adsorption.py

And Common Monomers:
https://github.com/Sulstice/global-chem/blob/master/global_chem/global_chem/materials/polymers/common_monomer_repeating_units.py

I

Are either of these acceptable to add to your awesome list?

Thank you.

**Comment by blokhin** [comment]
@Sulstice many thanks for posting! Is there any chance this is written as a markdown / plain text content? Not all the scientists are capable of reading the code.

**Comment by blokhin** [comment]
closing preliminary
