### ISSUE TITLE
what about granta?

### ISSUE THREAD

**Issue by ltalirz** [tilde-lab/awesome-materials-informatics#6]
One could argue that "machine readable materials databases" are their core business.
http://www.grantadesign.com/products/data/index.htm

Still, the focus is engineering rather than science, and the databases seem to differ from most of the ones listed here as many of them don't seem to go into atomic resolution of the material.
Should those be listed here as well?
If not, how to amend the criteria in order to exclude them?

**Comment by blokhin** [comment]
As far as I know, Granta isn't a data provider, rather an infrastructure integrator (_cf._ Granta MI).
