### ISSUE TITLE
computational materials science centers

### ISSUE THREAD

**Issue by ltalirz** [tilde-lab/awesome-materials-informatics#7]
Just came across this interesting and rather extensive list:
http://miccom-center.org/centers.html

Might be worth a link?

**Comment by blokhin** [comment]
Although eroded away with time, I think, there is still a subtle difference between the _computational materials science_ and _materials informatics_.

**Comment by blokhin** [comment]
@ltalirz what do you think?

**Comment by ltalirz** [comment]
I agree on both counts - there is a difference and it is eroding.
Many of the centers listed there have projects on this list.

I didn't provide a suggestion where to add the link, though, and we currently don't have a "useful links" section. Fine to close for the moment.
